# Übung - fehlende Werte

In dieser Übung wollen wir uns Grundtechnicken aneignen um fehlende Werte zu identifizieren. Bei der Identifizierung von fehlenden Werten geht es nicht nur darum die Missings zu finden, sondern dieser Part ermöglicht es dir gleichzeitig, systematische Fehler zu finden, die z.B. beim Datenabzug entstanden sind.

Was können systematische Fehler sein?

        - auffällig ist, dass fehlende Werte an bestimmten Stellen für bestimmte Felder vorkommen
        - wurden die Filter beim Datenabzug korrekt gesetzt? --> du möchtest dir nur das Jahr 2019 anschauen
          --> sind vlt auch Daten von 2018 oder 2020 enthalten?
        - Namen wurden nicht einheitlich geschrieben
          --> z.B. USA, U.S.A, America, Amerika, Vereinigten Staaten ...

**Aufgabe:**

Lese die csv Datei "fehlende_Werte_uebung" ein.
In den Daten sind 4 Spalten mit fehlenden Werten enthalten. Entdecke diese! Du kannst die fehlenden Werte erst einmal mit np.nan ersetzen. Ziel der Übung ist es, Techniken zu finden, die dir helfen Unstimmigkeiten im Datensatz zu finden.

Du kannst dir gern eine Zusammenfassung mit hilfreichen Funktionen notieren.

In [1]:
import pandas as pd
import numpy as np

In [22]:
df_e = pd.read_csv(r'fehlende_Werte_uebung.csv', sep='|', index_col=0 )
df_e

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8.0,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8.0,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8.0,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8.0,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8.0,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4.0,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4.0,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4.0,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4.0,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4.0,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [23]:
df_e.info()

<class 'pandas.core.frame.DataFrame'>
Index: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    object
 1   cylinders     398 non-null    float64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
 8   name          398 non-null    object
dtypes: float64(4), int64(2), object(3)
memory usage: 31.1+ KB

**Erster Fehler  in Spalte "horsepower" --> NaN-Werte**

In [24]:
df_e.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

In [25]:
# df_new = df_e.dropna()
df_e.dropna(inplace=True)
df_e.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

**2. Fehler: ? in Spalte 'mpg'**

In [26]:
# welche Autos haben Wert '?' in Spalte 'mpg'?
df_e[df_e['mpg']=='?']

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
12,?,8.0,400.0,150.0,3761,9.5,70,missing,chevrolet monte carlo
39,?,8.0,400.0,175.0,4464,11.5,71,usa,pontiac catalina brougham
46,?,4.0,140.0,72.0,2408,19.0,71,usa,chevrolet vega (sw)
69,?,8.0,350.0,160.0,4456,13.5,72,usa,oldsmobile delta 88 royale
113,?,6.0,155.0,107.0,2472,14.0,73,usa,mercury capri v6
150,?,4.0,108.0,93.0,2391,15.5,74,japan,subaru
220,?,4.0,85.0,70.0,1945,16.8,77,japan,datsun f-10 hatchback
264,?,8.0,302.0,139.0,3205,11.2,78,usa,ford futura
305,?,4.0,151.0,90.0,2670,16.0,79,usa,buick skylark limited

In [35]:
# df_e.drop(df_e[df_e['mpg']=='?'].index,inplace=True)   #entfernen
df_e = df_e[df_e['mpg'] != '?']             #filtern
df_e[df_e['mpg']=='?']

Empty DataFrame
Columns: [mpg, cylinders, displacement, horsepower, weight, acceleration, model_year, origin, name]
Index: []

**3. Fehler: Unlogischer Wert in Spalte 'cylinders'**

In [36]:
df_e['cylinders'].unique()

array([ 8.00000000e+00,  4.00000000e+00, -9.99999999e+07,  6.00000000e+00,
        3.00000000e+00,  5.00000000e+00])

In [ ]:
# df_e[~df_e['cylinders'].isin([3,4,5,6,8])]  #alles, was nicht in die Liste ist
df_e[df_e['cylinders']<0]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
15,22.0,-99999999.9,198.0,95.0,2833,15.5,70,usa,plymouth duster
41,14.0,-99999999.9,318.0,150.0,4096,13.0,71,usa,plymouth fury iii
42,12.0,-99999999.9,383.0,180.0,4955,11.5,71,usa,dodge monaco (sw)
44,13.0,-99999999.9,400.0,175.0,5140,12.0,71,usa,pontiac safari (sw)
89,15.0,-99999999.9,318.0,150.0,3777,12.5,73,usa,dodge coronet custom
90,12.0,-99999999.9,429.0,198.0,4952,11.5,73,usa,mercury marquis brougham
92,13.0,-99999999.9,351.0,158.0,4363,13.0,73,usa,ford ltd
157,15.0,-99999999.9,350.0,145.0,4440,14.0,75,usa,chevrolet bel air
158,16.0,-99999999.9,318.0,150.0,4498,14.5,75,usa,plymouth grand fury
229,16.0,-99999999.9,400.0,180.0,4220,11.1,77,usa,pontiac grand prix lj
230,15.5,-99999999.9,350.0,170.0,4165,11.4,77,usa,chevrolet monte carlo landau
231,15.5,-99999999.9,400.0,190.0,4325,12.2,77,usa,chrysler cordoba
232,16.0,-99999999.9,351.0,149.0,4335,14.5,77,usa,ford thunderbird

In [ ]:
df_e = df_e[df_e['cylinders'] > 0]  #filtern
df_e[df_e['cylinders']<0]

Empty DataFrame
Columns: [mpg, cylinders, displacement, horsepower, weight, acceleration, model_year, origin, name]
Index: []

In [39]:
df_e['origin'].unique()

array(['usa', 'japan', 'europe', 'missing'], dtype=object)

In [40]:
#missing entfernen
df_e = df_e[df_e['origin']!='missing']
df_e['origin'].unique()

array(['usa', 'japan', 'europe'], dtype=object)

In [42]:
df_e['model_year'].unique()

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82])

In [43]:
#Wenn ich zB nur bis zum Jahr 79 brauche
df_e = df_e[df_e['model_year']<80]
df_e['model_year'].unique()

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79])